/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-19T22:07:49.375680+02:00[Europe/Copenhagen]
 * <br>
*  The generated test suite contains 36 tests
 * <br>
*  Covered targets: 129
 * <br>
*  Used time: 2h 13m 29s
 * <br>
*  Needed budget for current results: 4%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class CrApiBlackBoxEvoMasterTest_faults_Test {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/identity/api/auth/forget-password
    * Using 1 example:
    *   (-) BODY -> adam007@example.com
    */
    @Test @Timeout(120)
    public void test_0_postOnForget_passwordReturnsMismatchResponseWithSchema() throws Exception {
        
        ValidatableResponse res_0 = given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"adam007@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("OTP Sent on the provided email, adam007@example.com"))
                .body("'status'", numberMatches(200));
        String location_forget_password__2 = res_0.extract().header("location");
        assertTrue(isValidURIorEmpty(location_forget_password__2));
        
        // Cleanup actions
        given().accept("application/json")
                .delete(resolveLocation(location_forget_password__2, baseUrlOfSut + "/identity/api/v2/admin/videos/256"))
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/forget-password
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_1_postOnForget_passwordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/forget-password'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"7MA\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'forgetPassword' on field 'email': rejected value [7MA]; codes [Email.forgetPassword.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [forgetPassword.email,email]; arguments []; default message [email],[Ljakarta.validation.constraints.Pattern$Flag;@88359c9,.*]; default message [must be a well-formed email address]"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/login
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) BODY -> Test!123
    */
    @Test @Timeout(120)
    public void test_2_postOnLoginReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/login'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"nA\", " + 
                    " \"password\" : \"Test!123\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/login")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'loginForm' on field 'email': rejected value [nA]; codes [Size.loginForm.email,Size.email,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [loginForm.email,email]; arguments []; default message [email],100,3]; default message [size must be between 3 and 100]"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/login
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_3_postOnLoginReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/login'.
        given().accept("*/*")
                .contentType("application/json")
                .post(baseUrlOfSut + "/identity/api/auth/login")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/login"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/signup
    * Found 1 potential fault of type-code 101
    * Using 3 examples:
    *   (-) BODY -> 5hmb0gvyC__hVQg
    *   (-) BODY -> 6915656974
    *   (-) BODY -> Cristobal.Weissnat@example.com
    */
    @Test @Timeout(120)
    public void test_4_postOnSignupReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/signup'.
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\" : \"\", " + 
                    " \"number\" : \"6915656974\", " + 
                    " \"password\" : \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 2 errors\nField error in object 'signUpForm' on field 'name': rejected value []; codes [Size.signUpForm.name,Size.name,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signUpForm.name,name]; arguments []; default message [name],100,3]; default message [size must be between 3 and 100]\nField error in object 'signUpForm' on field 'name': rejected value []; codes [NotBlank.signUpForm.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signUpForm.name,name]; arguments []; default message [name]]; default message [must not be blank]"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/forget-password
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_5_postOnForget_passwordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/forget-password'.
        given().accept("*/*")
                .contentType("application/json")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/forget-password"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/signup
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_6_postOnSignupReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/signup'.
        given().accept("*/*")
                .contentType("application/json")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/signup"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/identity/api/auth/v3/check-otp
    * Found 2 potential faults. Type-codes: 100, 101
    * Using 3 examples:
    *   (-) BODY -> 5hmb0gvyC__hVQg
    *   (-) BODY -> 9969
    *   (-) BODY -> Cristobal.Weissnat@example.com
    */
    @Test @Timeout(120)
    public void test_7_postOnCheck_otpShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'Otp': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"Otp was not found for parameters {OTP Details Not Found=Cristobal.Weissnat@example.com}"; line: 1, column: 4].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\" : \"9969\", " + 
                    " \"password\" : \"5hmb0gvyC__hVQg\", " + 
                    " \"email\" : \"Cristobal.Weissnat@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body(containsString("Otp was not found for parameters {OTP Details Not Found=Cristobal.Weissnat@example.com}"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/identity/api/auth/v2/check-otp
    * Found 1 potential fault of type-code 100
    * Using 3 examples:
    *   (-) BODY -> 5hmb0gvyC__hVQg
    *   (-) BODY -> 9969
    *   (-) BODY -> Cristobal.Weissnat@example.com
    */
    @Test @Timeout(120)
    public void test_8_postOnCheck_otpCauses500_internalServerError() throws Exception {
        
        // Fault100. HTTP Status 500.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\" : \"9969\", " + 
                    " \"password\" : \"5hmb0gvyC__hVQg\", " + 
                    " \"email\" : \"Cristobal.Weissnat@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v2/check-otp")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("Otp was not found for parameters {OTP Details Not Found=Cristobal.Weissnat@example.com}"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/identity/api/auth/v3/check-otp
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_9_postOnCheck_otpReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/identity/api/auth/v3/check-otp'.
        given().accept("*/*")
                .contentType("application/json")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/v3/check-otp"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/vehicle/vehicles
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_10_getOnVehiclesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/vehicle/vehicles")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/user/verify-email-token
    * Found 1 potential fault of type-code 101
    * Using 3 examples:
    *   (-) BODY -> Danielle.Ankunding@example.com
    *   (-) BODY -> Einar.Swaniawski@example.com
    *   (-) BODY -> T9O2s6i3C7o2E8l7X5Y4
    */
    @Test @Timeout(120)
    public void test_11_postOnVerify_email_tokenReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"old_email\" : \"Einar.Swaniawski@example.com\", " + 
                    " \"new_email\" : \"Danielle.Ankunding@example.com\", " + 
                    " \"token\" : \"T9O2s6i3C7o2E8l7X5Y4\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/v2/user/verify-email-token")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/user/change-email
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) BODY -> Cristobal.Weissnat@example.com
    *   (-) BODY -> Sofia.Predovic@example.com
    */
    @Test @Timeout(120)
    public void test_12_postOnChange_emailReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"new_email\" : \"Sofia.Predovic@example.com\", " + 
                    " \"old_email\" : \"Cristobal.Weissnat@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/v2/user/change-email")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/user/videos
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_13_postOnVideosReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/identity/api/v2/user/videos")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/vehicle/add_vehicle
    * Found 1 potential fault of type-code 101
    * Using 2 examples:
    *   (-) BODY -> 0IOJO38SMVL663989
    *   (-) BODY -> 9896
    */
    @Test @Timeout(120)
    public void test_14_postOnAdd_vehicleReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"pincode\" : \"9896\", " + 
                    " \"vin\" : \"0IOJO38SMVL663989\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/v2/vehicle/add_vehicle")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/vehicle/resend_email
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_15_postOnResend_emailReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .post(baseUrlOfSut + "/identity/api/v2/vehicle/resend_email")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/user/pictures
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_16_postOnPicturesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/identity/api/v2/user/pictures")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/identity/api/v2/user/reset-password
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_17_postOnReset_passwordReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"oD9Qg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/v2/user/reset-password")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/identity/api/auth/v2.7/user/login-with-token
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(120)
    public void test_18_postOnLogin_with_tokenShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/identity/api/auth/v2.7/user/login-with-token'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"tcQ91Gls\", " + 
                    " \"token\" : \"3rq5hE9v3xPFoX\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v2.7/user/login-with-token")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'token'", nullValue())
                .body("'type'", containsString(""))
                .body("'message'", containsString("Invalid Credentials"))
                .body("'mfaRequired'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/convert_video
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) QUERY: video_id -> 1
    */
    @Test @Timeout(120)
    public void test_19_getOnConvert_videoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: video_id -> 1
    */
    @Test @Timeout(120)
    public void test_20_getOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/vehicle/{vehicleId}/location
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: vehicleId -> 1929186d-8b67-4163-a208-de52a41f7301
    */
    @Test @Timeout(120)
    public void test_21_getOnLocationReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/vehicle/1929186d-8b67-4163-a208-de52a41f7301/location")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/convert_video
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_22_getOnVideosConvert_videoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_23_getOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/373")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_24_getOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/-1714431330758838045")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/convert_video
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_25_getOnConvert_videoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=682")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/identity/api/v2/user/videos/convert_video
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_26_getOnVideosConvert_videoWithQueryParamNegativeVideo_idReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=-6097841521977003510")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: video_id -> 10
    */
    @Test @Timeout(120)
    public void test_27_putOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"videoName\" : \"vehicle.mp4\" " + 
                    " } ")
                .put(baseUrlOfSut + "/identity/api/v2/user/videos/10")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_28_putOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"videoName\" : \"GkOig3N3Oa\", " + 
                    " \"video_url\" : \"6fKF1WIkKg\", " + 
                    " \"conversion_params\" : \"jH05r37WyVkV\" " + 
                    " } ")
                .put(baseUrlOfSut + "/identity/api/v2/user/videos/435")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_29_putOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : -1832601196 " + 
                    " } ")
                .put(baseUrlOfSut + "/identity/api/v2/user/videos/-1789447159377465239")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/admin/videos/{video_id}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: video_id -> 12345
    */
    @Test @Timeout(120)
    public void test_30_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/12345")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (-) PATH: video_id -> 1
    */
    @Test @Timeout(120)
    public void test_31_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_32_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/386")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/user/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_33_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/-4034828940481324228")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/admin/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_34_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/289")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/identity/api/v2/admin/videos/{video_id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(120)
    public void test_35_deleteOnVideoReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.invalidJson Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/-4422599566068052018")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }


}
