/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-19T22:07:49.406880+02:00[Europe/Copenhagen]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 7
 * <br>
*  Used time: 2h 13m 29s
 * <br>
*  Needed budget for current results: 4%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class CrApiBlackBoxEvoMasterTest_successes_Test {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/identity/api/auth/login
    * Using 2 examples:
    *   (-) BODY -> Test!123
    *   (-) BODY -> test@example.com
    */
    @Test @Timeout(120)
    public void test_0_postOnLoginReturns200() throws Exception {
        
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"test@example.com\", " + 
                    " \"password\" : \"Test!123\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/login")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'token'", containsString("eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzc2NjI0MzMyLCJleHAiOjE3NzcyMjkxMzIsInJvbGUiOiJ1c2VyIn0.AmMUGNAtuQNihTFdtOxEinjatw-VH9gODgQ8GSylnhhZIlVm7JDpXNmQmnkpmLJsNfN4dub3NSfxnyQayjjJfvDXPY_ySOXLUhioXqNGpiVT83IaZVLBdkYK0MBRrbgxg8-htAG1fMmhl-TzZXSaisSUnzDvmG0lVZEv1O0OQFTEQd9ah_rMCjwIO6pnsQ2Bjake0x-H2guMVfxNR_zkO08b9Sv6OZp9Gay1_kYvvlWYxMd34j1ZDBodiALOqsPGTeOi9WcVwyhs5AoZeTwMdllA4UDaNW8MmOSagFGaKXIe1r8avJjYny4lmHb5R-fwLrBoKWxH8k5yHf3x3p6jkA"))
                .body("'type'", containsString("Bearer"))
                .body("'message'", containsString("Login successful"))
                .body("'mfaRequired'", equalTo(false));
    }


}
