/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-19T22:07:49.407743+02:00[Europe/Copenhagen]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 12
 * <br>
*  Used time: 2h 13m 29s
 * <br>
*  Needed budget for current results: 4%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class CrApiBlackBoxEvoMasterTest_others_Test {

    
    private static String baseUrlOfSut = "http://localhost:8888";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (403) POST:/identity/api/auth/signup
    * Using 4 examples:
    *   (-) BODY -> 5hmb0gvyC__hVQg
    *   (-) BODY -> 6915656974
    *   (-) BODY -> Cristobal.Weissnat
    *   (-) BODY -> Cristobal.Weissnat@example.com
    */
    @Test @Timeout(120)
    public void test_0_postOnSignupReturns403() throws Exception {
        
        given().accept("application/json")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\" : \"Cristobal.Weissnat\", " + 
                    " \"number\" : \"6915656974\", " + 
                    " \"password\" : \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Number already registered! Number: 6915656974"))
                .body("'status'", numberMatches(403));
    }
    
    
    /**
    * Calls:
    * (404) GET:/identity/api/v2/user/dashboard
    */
    @Test @Timeout(120)
    public void test_1_getOnDashboardReturns404() throws Exception {
        
        given().accept("application/json")
                .get(baseUrlOfSut + "/identity/api/v2/user/dashboard")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Given Email is not registered! "))
                .body("'status'", numberMatches(404));
    }
    
    
    /**
    * Calls:
    * (403) POST:/identity/api/auth/v4.0/user/login-with-token
    */
    @Test @Timeout(120)
    public void test_2_postOnLogin_with_tokenReturns403() throws Exception {
        
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"jSE\", " + 
                    " \"token\" : \"jgHR1EqCNTBNWZKr\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v4.0/user/login-with-token")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Our security team made us remove the \"Login with token\" feature because it's not secure enough. It's not available after API version 2.7"))
                .body("'status'", numberMatches(403));
    }


}
