import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T12:04:04.756364566Z[Etc/UTC]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 130
 * <br>
*  Used time: 1h 3m 39s
 * <br>
*  Needed budget for current results: 94%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
*/
public class CrApiCommunityEvoMasterTest_others {

    
    private static final SutHandler controller = new org.evomaster.driver.CrApiCommunityController("/opt/crapi/identity-service.jar");
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    @Test @Timeout(60)
    public void test_0() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"_EM_25_XYZ_\", " + 
                    " \"token\": \"VzJo\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v4.0/user/login-with-token")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Our security team made us remove the \"Login with token\" feature because it's not secure enough. It's not available after API version 2.7"))
                .body("'status'", numberMatches(403.0));
    }
    
    
    @Test @Timeout(60)
    public void test_1() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/dashboard")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Given Email is not registered! "))
                .body("'status'", numberMatches(404.0));
    }
    
    
    @Test @Timeout(60)
    public void test_2() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_260_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"adam007@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Given Email is not registered! adam007@example.com"))
                .body("'status'", numberMatches(404.0));
    }


}
