import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-15T12:04:04.654207177Z[Etc/UTC]
 * <br>
*  The generated test suite contains 95 tests
 * <br>
*  Covered targets: 876
 * <br>
*  Used time: 1h 3m 39s
 * <br>
*  Needed budget for current results: 94%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class CrApiCommunityEvoMasterTest_faults {

    
    private static final SutHandler controller = new org.evomaster.driver.CrApiCommunityController("/opt/crapi/identity-service.jar");
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    @Test @Timeout(60)
    public void test_0_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/config/JwtAuthTokenFilter_83_doFilterInternal POST:/identity/api/auth/v2.7/user/login-with-token
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v2.7/user/login-with-token -> Response status 500 not defined for path '/identity/api/auth/v2.7/user/login-with-token'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"U8sEBk8u2\", " + 
                    " \"token\": \"_EM_26_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v2.7/user/login-with-token")
                .then()
                .statusCode(500)// com/crapi/config/JwtAuthTokenFilter_83_doFilterInternal
                .assertThat()
                .contentType("application/json")
                .body("'token'", nullValue())
                .body("'type'", containsString(""))
                .body("'message'", containsString("Invalid Credentials"))
                .body("'mfaRequired'", equalTo(false));
    }
    
    
    @Test @Timeout(60)
    public void test_1_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_92_validateOtp POST:/identity/api/auth/v2/check-otp
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_31_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"PvCL\", " + 
                    " \"password\": \"JZfbjeDZ4\", " + 
                    " \"email\": \"LbcLiLBHO4M5Rf\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v2/check-otp?EMextraParam123=42")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_92_validateOtp
                .assertThat()
                .contentType("text/plain")
                .body(containsString("User was not found for parameters {userEmail=LbcLiLBHO4M5Rf}"));
    }
    
    
    @Test @Timeout(60)
    public void test_2_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=Cristobal.Weissnat@example.com}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"jJy\", " + 
                    " \"password\": \"_EM_244_XYZ_\", " + 
                    " \"email\": \"Cristobal.Weissnat@example.com\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp?EMextraParam123=42")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=Cristobal.Weissnat@example.com}"));
    }
    
    
    @Test @Timeout(60)
    public void test_3_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=HLLujLtDgzt}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"hZO\", " + 
                    " \"password\": \"_EM_236_XYZ_\", " + 
                    " \"email\": \"HLLujLtDgzt\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp?EMextraParam123=_EM_237_XYZ_")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=HLLujLtDgzt}"));
    }
    
    
    @Test @Timeout(60)
    public void test_4_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=_EM_377_XYZ_}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"9969\", " + 
                    " \"password\": \"u__Ru2DVzHJAhu4J\", " + 
                    " \"email\": \"_EM_377_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=_EM_377_XYZ_}"));
    }
    
    
    @Test @Timeout(60)
    public void test_5_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=_EM_444_XYZ_}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"ie3p\", " + 
                    " \"password\": \"_EM_443_XYZ_\", " + 
                    " \"email\": \"_EM_444_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=_EM_444_XYZ_}"));
    }
    
    
    @Test @Timeout(60)
    public void test_6_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=p7pHENZcI}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"VLd\", " + 
                    " \"password\": \"6Saz30\", " + 
                    " \"email\": \"p7pHENZcI\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=p7pHENZcI}"));
    }
    
    
    @Test @Timeout(60)
    public void test_7_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=_EM_245_XYZ_}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"jJ{\", " + 
                    " \"password\": \"fRHJ42\", " + 
                    " \"email\": \"_EM_245_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=_EM_245_XYZ_}"));
    }
    
    
    @Test @Timeout(60)
    public void test_8_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=tp0MmTgglwyE}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"kDn\", " + 
                    " \"password\": \"LDyvV\", " + 
                    " \"email\": \"tp0MmTgglwyE\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=tp0MmTgglwyE}"));
    }
    
    
    @Test @Timeout(60)
    public void test_9_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=fL0eiKgOcR_VqI}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"9969\", " + 
                    " \"password\": \"u__Ru2DVzHJAhu4J\", " + 
                    " \"email\": \"fL0eiKgOcR_VqI\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=fL0eiKgOcR_VqI}"));
    }
    
    
    @Test @Timeout(60)
    public void test_10_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=fL0eiKgOcR_VqIj}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"rmaX\", " + 
                    " \"password\": \"u__Ru2DVzHJAhu4J\", " + 
                    " \"email\": \"fL0eiKgOcR_VqIj\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=fL0eiKgOcR_VqIj}"));
    }
    
    
    @Test @Timeout(60)
    public void test_11_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=YeGruCY7P1G}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"jJ{\", " + 
                    " \"password\": \"fRHJ42\", " + 
                    " \"email\": \"YeGruCY7P1G\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=YeGruCY7P1G}"));
    }
    
    
    @Test @Timeout(60)
    public void test_12_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=_EM_998_XYZ_}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"rmaX\", " + 
                    " \"password\": \"u__Ru2DVzHJAhu4J\", " + 
                    " \"email\": \"_EM_998_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=_EM_998_XYZ_}"));
    }
    
    
    @Test @Timeout(60)
    public void test_13_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=VYEotu8}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"rm`X\", " + 
                    " \"password\": \"u__Ru2DVyHJAhu4J\", " + 
                    " \"email\": \"VYEotu8\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=VYEotu8}"));
    }
    
    
    @Test @Timeout(60)
    public void test_14_with500() throws Exception {
        
        // Fault100. HTTP Status 500. com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp POST:/identity/api/auth/v3/check-otp
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Unable to parse JSON - Unrecognized token 'User': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"User was not found for parameters {userEmail=8hAWtQSP}"; line: 1, column: 5].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"otp\": \"9969\", " + 
                    " \"password\": \"Fq2TDdjUC0hEz\", " + 
                    " \"email\": \"8hAWtQSP\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp")
                .then()
                .statusCode(500)// com/crapi/service/Impl/OtpServiceImpl_124_secureValidateOtp
                .assertThat()
                .contentType("application/json")
                .body(containsString("User was not found for parameters {userEmail=8hAWtQSP}"));
    }
    
    
    @Test @Timeout(60)
    public void test_15() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/management/users/all")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\": \"9xnm51opvvgcxg0\", " + 
                    " \"number\": \"_EM_1003_XYZ_\", " + 
                    " \"password\": \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("User registered successfully! Please Login."))
                .body("'status'", numberMatches(200.0));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\": \"9xnm51opvvgcxg0\", " + 
                    " \"number\": \"_EM_1003_XYZ_\", " + 
                    " \"password\": \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Number already registered! Number: _EM_1003_XYZ_"))
                .body("'status'", numberMatches(403.0));
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/community/api/v2/community/posts -> Response status 401 not defined for path '/community/api/v2/community/posts'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"title\": \"xKwA\" " + 
                    " } ")
                .post(baseUrlOfSut + "/community/api/v2/community/posts")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_16() throws Exception {
        
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/forget-password -> Response status 400 not defined for path '/identity/api/auth/forget-password'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"eRvL\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'forgetPassword' on field 'email': rejected value [eRvL]; codes [Email.forgetPassword.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [forgetPassword.email,email]; arguments []; default message [email],[Ljakarta.validation.constraints.Pattern$Flag;@31c14fec,.*]; default message [must be a well-formed email address]"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\": \"9xnm51opvvgcxg0\", " + 
                    " \"number\": \"5ETFbnWZsR6U\", " + 
                    " \"password\": \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("User registered successfully! Please Login."))
                .body("'status'", numberMatches(200.0));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"Cristobal.Weissnat@example.com\", " + 
                    " \"name\": \"9xnm51opvvgcxg0\", " + 
                    " \"number\": \"_EM_693_XYZ_\", " + 
                    " \"password\": \"5hmb0gvyC__hVQg\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Email already registered! Email: Cristobal.Weissnat@example.com"))
                .body("'status'", numberMatches(403.0));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/community/api/v2/community/posts")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_17() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/v3/check-otp -> Response status 400 not defined for path '/identity/api/auth/v3/check-otp'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/auth/v3/check-otp?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400.0))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/v3/check-otp"));
    }
    
    
    @Test @Timeout(60)
    public void test_18() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/forget-password -> Response status 400 not defined for path '/identity/api/auth/forget-password'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400.0))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/forget-password"));
    }
    
    
    @Test @Timeout(60)
    public void test_19() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/signup -> Response status 400 not defined for path '/identity/api/auth/signup'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/auth/signup")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400.0))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/signup"));
    }
    
    
    @Test @Timeout(60)
    public void test_20() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/login -> Response status 400 not defined for path '/identity/api/auth/login'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/auth/login")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/problem+json")
                .body("'type'", containsString("about:blank"))
                .body("'title'", containsString("Bad Request"))
                .body("'status'", numberMatches(400.0))
                .body("'detail'", containsString("Failed to read request"))
                .body("'instance'", containsString("/identity/api/auth/login"));
    }
    
    
    @Test @Timeout(60)
    public void test_21() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/forget-password -> Response status 400 not defined for path '/identity/api/auth/forget-password'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_128_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"ncuk\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/forget-password?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'forgetPassword' on field 'email': rejected value [ncuk]; codes [Email.forgetPassword.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [forgetPassword.email,email]; arguments []; default message [email],[Ljakarta.validation.constraints.Pattern$Flag;@31c14fec,.*]; default message [must be a well-formed email address]"));
    }
    
    
    @Test @Timeout(60)
    public void test_22() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/signup -> Response status 400 not defined for path '/identity/api/auth/signup'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"A\", " + 
                    " \"name\": \"Cristobal.Weissnat\", " + 
                    " \"number\": \"Jo3\", " + 
                    " \"password\": \"_EM_49_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/signup?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Validation failed"))
                .body("'details'", containsString("org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'signUpForm' on field 'email': rejected value [A]; codes [Email.signUpForm.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [signUpForm.email,email]; arguments []; default message [email],[Ljakarta.validation.constraints.Pattern$Flag;@31c14fec,.*]; default message [must be a well-formed email address]"));
    }
    
    
    @Test @Timeout(60)
    public void test_23() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/vehicle/{vehicleId}/location -> Response status 401 not defined for path '/identity/api/v2/vehicle/{vehicleId}/location'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/vehicle/Iql/location?EMextraParam123=_EM_6_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_24() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/vehicle/vehicles -> Response status 401 not defined for path '/identity/api/v2/vehicle/vehicles'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_9_XYZ_")
                .get(baseUrlOfSut + "/identity/api/v2/vehicle/vehicles")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_25() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/{postId} -> Response status 401 not defined for path '/community/api/v2/community/posts/{postId}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/_EM_10_XYZ_?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_26() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/products -> Response status 401 not defined for path '/workshop/api/shop/products'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/products")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_27() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/ -> Response status 401 not defined for path '/workshop/api/mechanic/'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/?EMextraParam123=_EM_23_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_28() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/vehicle/resend_email -> Response status 401 not defined for path '/identity/api/v2/vehicle/resend_email'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/identity/api/v2/vehicle/resend_email?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_29() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/375")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_30() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_3_XYZ_")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_31() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/convert_video -> Response status 401 not defined for path '/identity/api/v2/user/videos/convert_video'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_32() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/admin/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/admin/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/582?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_33() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_13_XYZ_")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/766")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_34() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/return_qr_code -> Response status 401 not defined for path '/workshop/api/shop/return_qr_code'.
        given().accept("")
                .header("Accept", "*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/return_qr_code")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_35() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/community/api/v2/community/posts/{postId}/comment -> Response status 401 not defined for path '/community/api/v2/community/posts/{postId}/comment'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/community/api/v2/community/posts/4KN9hM/comment?EMextraParam123=_EM_27_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_36() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/user/reset-password -> Response status 401 not defined for path '/identity/api/v2/user/reset-password'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/v2/user/reset-password")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_37() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/user/change-email -> Response status 401 not defined for path '/identity/api/v2/user/change-email'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/v2/user/change-email")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_38() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/user/verify-email-token -> Response status 401 not defined for path '/identity/api/v2/user/verify-email-token'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_39_XYZ_")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/identity/api/v2/user/verify-email-token")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_39() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/user/pictures -> Response status 401 not defined for path '/identity/api/v2/user/pictures'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_41_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("file=_EM_40_XYZ_")
                .post(baseUrlOfSut + "/identity/api/v2/user/pictures")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_40() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/user/videos -> Response status 401 not defined for path '/identity/api/v2/user/videos'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/x-www-form-urlencoded")
                .body("file=SS7a")
                .post(baseUrlOfSut + "/identity/api/v2/user/videos")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_41() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/v2/vehicle/add_vehicle -> Response status 401 not defined for path '/identity/api/v2/vehicle/add_vehicle'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"pincode\": \"_EM_43_XYZ_\", " + 
                    " \"vin\": \"j4Fs5_OmeaYa\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/v2/vehicle/add_vehicle")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_42() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/community/api/v2/coupon/new-coupon -> Response status 401 not defined for path '/community/api/v2/coupon/new-coupon'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_46_XYZ_")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/community/api/v2/coupon/new-coupon")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_43() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/community/api/v2/coupon/validate-coupon -> Response status 401 not defined for path '/community/api/v2/coupon/validate-coupon'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"coupon_code\": \"bX0Muc\" " + 
                    " } ")
                .post(baseUrlOfSut + "/community/api/v2/coupon/validate-coupon")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_44() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/community/api/v2/community/posts -> Response status 401 not defined for path '/community/api/v2/community/posts'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/community/api/v2/community/posts")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_45() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/products -> Response status 401 not defined for path '/workshop/api/shop/products'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"nOZn3xIi\", " + 
                    " \"price\": \"_EM_53_XYZ_\", " + 
                    " \"image_url\": \"A8PV6qejavxiRYin\" " + 
                    " } ")
                .post(baseUrlOfSut + "/workshop/api/shop/products?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_46() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/orders -> Response status 401 not defined for path '/workshop/api/shop/orders'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"product_id\": 16, " + 
                    " \"quantity\": 894 " + 
                    " } ")
                .post(baseUrlOfSut + "/workshop/api/shop/orders?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_47() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/apply_coupon -> Response status 401 not defined for path '/workshop/api/shop/apply_coupon'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/workshop/api/shop/apply_coupon")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_48() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/merchant/contact_mechanic -> Response status 401 not defined for path '/workshop/api/merchant/contact_mechanic'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_58_XYZ_")
                .contentType("application/json")
                .body(" null ")
                .post(baseUrlOfSut + "/workshop/api/merchant/contact_mechanic")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_49() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/mechanic/signup -> Response status 401 not defined for path '/workshop/api/mechanic/signup'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"k\", " + 
                    " \"email\": \"_EM_59_XYZ_\", " + 
                    " \"number\": \"_EM_60_XYZ_\", " + 
                    " \"password\": \"_EM_61_XYZ_\", " + 
                    " \"mechanic_code\": \"faG\" " + 
                    " } ")
                .post(baseUrlOfSut + "/workshop/api/mechanic/signup")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_50() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/admin/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/admin/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/12345")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_51() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/admin/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/admin/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/identity/api/v2/admin/videos/-65029")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_52() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/740")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_53() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_54() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/-64624")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_55() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/-4611686018427387392")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_56() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_57() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. DELETE:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .delete(baseUrlOfSut + "/identity/api/v2/user/videos/-4611686018427387392")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_58() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/convert_video -> Response status 401 not defined for path '/identity/api/v2/user/videos/convert_video'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=-768274656709759695")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_59() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_60() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/mechanic_report -> Response status 401 not defined for path '/workshop/api/mechanic/mechanic_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_20_XYZ_")
                .get(baseUrlOfSut + "/workshop/api/mechanic/mechanic_report?" + 
                    "report_id=87&" + 
                    "EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_61() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/orders/return_order -> Response status 401 not defined for path '/workshop/api/shop/orders/return_order'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_47_XYZ_")
                .post(baseUrlOfSut + "/workshop/api/shop/orders/return_order?" + 
                    "order_id=218&" + 
                    "EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_62() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/management/users/all")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_63() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": 582, " + 
                    " \"video_url\": \"_EM_62_XYZ_\" " + 
                    " } ")
                .put(baseUrlOfSut + "/identity/api/v2/user/videos/41?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_64() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"product_id\": 622, " + 
                    " \"quantity\": 1 " + 
                    " } ")
                .put(baseUrlOfSut + "/workshop/api/shop/orders/721")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_65() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/convert_video -> Response status 401 not defined for path '/identity/api/v2/user/videos/convert_video'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=2037252398")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_66() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/mechanic_report -> Response status 401 not defined for path '/workshop/api/mechanic/mechanic_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/mechanic_report?report_id=-8112")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_67() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/identity/api/v2/user/videos/convert_video -> Response status 401 not defined for path '/identity/api/v2/user/videos/convert_video'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/identity/api/v2/user/videos/convert_video?video_id=1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_68() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/orders/return_order -> Response status 401 not defined for path '/workshop/api/shop/orders/return_order'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/workshop/api/shop/orders/return_order?order_id=33")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_69() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/mechanic_report -> Response status 401 not defined for path '/workshop/api/mechanic/mechanic_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/mechanic_report?report_id=2")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_70() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/workshop/api/shop/orders/return_order -> Response status 401 not defined for path '/workshop/api/shop/orders/return_order'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/workshop/api/shop/orders/return_order?order_id=-1073741341")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_71() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/identity/api/v2/user/videos/{video_id} -> Response status 401 not defined for path '/identity/api/v2/user/videos/{video_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": 582, " + 
                    " \"video_url\": \"_EM_62_XYZ_\" " + 
                    " } ")
                .put(baseUrlOfSut + "/identity/api/v2/user/videos/10")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_72() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"product_id\": 1, " + 
                    " \"quantity\": 321 " + 
                    " } ")
                .put(baseUrlOfSut + "/workshop/api/shop/orders/-276227244")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_73() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. PUT:/workshop/api/shop/orders/{order_id} -> Response status 401 not defined for path '/workshop/api/shop/orders/{order_id}'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"product_id\": 781, " + 
                    " \"quantity\": 330 " + 
                    " } ")
                .put(baseUrlOfSut + "/workshop/api/shop/orders/1")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_74() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?offset=22")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_75() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_161_XYZ_")
                .get(baseUrlOfSut + "/workshop/api/management/users/all?" + 
                    "offset=870&" + 
                    "EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_76() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/management/users/all?offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_77() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?" + 
                    "limit=265&" + 
                    "offset=543&" + 
                    "EMextraParam123=_EM_115_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_78() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/all -> Response status 401 not defined for path '/workshop/api/shop/orders/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/all?" + 
                    "limit=30&" + 
                    "offset=173")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_79() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/workshop/api/management/users/all?" + 
                    "limit=1&" + 
                    "offset=846&" + 
                    "EMextraParam123=_EM_14_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_80() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/receive_report -> Response status 401 not defined for path '/workshop/api/mechanic/receive_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/workshop/api/mechanic/receive_report?" + 
                    "mechanic_code=_EM_18_XYZ_&" + 
                    "problem_details=My+car+has+engine+trouble%2C+and+I+need+urgent+help%21&" + 
                    "vin=z4rYT")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_81() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/service_requests -> Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/service_requests?" + 
                    "limit=516&" + 
                    "offset=357")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_82() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/receive_report -> Response status 401 not defined for path '/workshop/api/mechanic/receive_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/receive_report?" + 
                    "mechanic_code=TRAC_MECH1&" + 
                    "problem_details=_EM_100_XYZ_&" + 
                    "vin=_EM_101_XYZ_&" + 
                    "EMextraParam123=_EM_102_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_83() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/all -> Response status 401 not defined for path '/workshop/api/shop/orders/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/all?" + 
                    "limit=815&" + 
                    "offset=0&" + 
                    "EMextraParam123=_EM_163_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_84() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/service_requests -> Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/service_requests?" + 
                    "limit=30&" + 
                    "offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_85() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/receive_report -> Response status 401 not defined for path '/workshop/api/mechanic/receive_report'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/receive_report?" + 
                    "mechanic_code=_EM_331_XYZ_&" + 
                    "problem_details=kPiJW_A5wi&" + 
                    "vin=0BZCX25UTBJ987271")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_86() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/management/users/all?" + 
                    "limit=324&" + 
                    "offset=-961570677")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_87() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?" + 
                    "limit=895&" + 
                    "offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_88() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?" + 
                    "limit=-31873&" + 
                    "offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_89() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/all -> Response status 401 not defined for path '/workshop/api/shop/orders/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/all?" + 
                    "limit=276&" + 
                    "offset=-130110")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_90() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/shop/orders/all -> Response status 401 not defined for path '/workshop/api/shop/orders/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/shop/orders/all?" + 
                    "limit=-64762&" + 
                    "offset=47")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_91() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/management/users/all -> Response status 401 not defined for path '/workshop/api/management/users/all'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/management/users/all?" + 
                    "limit=-4053&" + 
                    "offset=19")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_92() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/workshop/api/mechanic/service_requests -> Unable to parse JSON - Unrecognized token 'CRAPIResponse': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')  at [Source: (String)"CRAPIResponse(message=Invalid Token, status=401) "; line: 1, column: 14].
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/workshop/api/mechanic/service_requests?" + 
                    "limit=-1368&" + 
                    "offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_93() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. GET:/community/api/v2/community/posts/recent -> Response status 401 not defined for path '/community/api/v2/community/posts/recent'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/community/api/v2/community/posts/recent?" + 
                    "limit=30&" + 
                    "offset=0")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body(containsString("CRAPIResponse(message=Invalid Token, status=401)"));
    }
    
    
    @Test @Timeout(60)
    public void test_94() throws Exception {
        
        // Fault200. Received A Response From API That Is Not Valid According To Its Schema. POST:/identity/api/auth/login -> Response status 401 not defined for path '/identity/api/auth/login'.
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\": \"Vsw2v\", " + 
                    " \"password\": \"Jj11\" " + 
                    " } ")
                .post(baseUrlOfSut + "/identity/api/auth/login?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'token'", nullValue())
                .body("'type'", containsString(""))
                .body("'message'", containsString("Given Email is not registered! "))
                .body("'mfaRequired'", equalTo(false));
    }


}
