#!/usr/bin/env bash
# =============================================================================
# run-report.sh
#
# Compiles and runs the JUnit 5 tests generated by EvoMaster and produces an
# HTML Surefire report.
#
# Steps:
#   1.  Detect the Java package declared in the generated .java files.
#   2.  Copy the .java files into the test-runner Maven project source tree.
#   3.  Run `mvn test` to compile and execute the tests against the live SUT.
#   4.  Run `mvn surefire-report:report` to generate the HTML report.
#   5.  Print the path to the HTML report.
#
# Usage:
#   bash scripts/run-report.sh [--tests-dir <dir>] [--sut-base-url <url>]
#
# Options:
#   --tests-dir    <dir>   Directory containing the generated .java files
#                          (default: ./generated_tests)
#   --sut-base-url <url>   Base URL of the running SUT used when the tests
#                          were generated (default: http://localhost:8080)
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
TESTS_DIR="$(pwd)/generated_tests"
SUT_BASE_URL="http://localhost:8080"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RUNNER_DIR="${REPO_ROOT}/test-runner"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tests-dir)    TESTS_DIR="$2";    shift 2 ;;
    --sut-base-url) SUT_BASE_URL="$2"; shift 2 ;;
    *) echo "[ERROR] Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()  { echo "[INFO]  $*"; }
error() { echo "[ERROR] $*" >&2; }

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if [[ ! -d "${TESTS_DIR}" ]]; then
  error "Tests directory not found: ${TESTS_DIR}"
  error "Run scripts/run-whitebox.sh first to generate tests."
  exit 1
fi

JAVA_FILES=( "${TESTS_DIR}"/*.java )
if [[ ! -f "${JAVA_FILES[0]}" ]]; then
  error "No .java files found in ${TESTS_DIR}"
  error "Run scripts/run-whitebox.sh first to generate tests."
  exit 1
fi

if ! command -v mvn &>/dev/null; then
  error "Maven (mvn) not found. Install Maven and re-run."
  exit 1
fi

if [[ ! -f "${RUNNER_DIR}/pom.xml" ]]; then
  error "test-runner/pom.xml not found at ${RUNNER_DIR}"
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. Detect the Java package declared in the generated .java files.
# ---------------------------------------------------------------------------
PACKAGE=""
for f in "${JAVA_FILES[@]}"; do
  PKG_LINE=$(grep -m1 "^package " "${f}" || true)
  if [[ -n "${PKG_LINE}" ]]; then
    # Extract the package name, stripping "package " prefix and trailing ";"
    PACKAGE=$(echo "${PKG_LINE}" | sed 's/^package //;s/;//;s/[[:space:]]//g')
    break
  fi
done

if [[ -n "${PACKAGE}" ]]; then
  info "Detected package: ${PACKAGE}"
  # Convert package notation (a.b.c) to directory path (a/b/c)
  PKG_PATH="${PACKAGE//.//}"
else
  info "No package declaration found; using default (root) package."
  PKG_PATH=""
fi

# ---------------------------------------------------------------------------
# 2. Copy the .java files into the test-runner Maven test source tree.
# ---------------------------------------------------------------------------
if [[ -n "${PKG_PATH}" ]]; then
  TEST_SRC_DIR="${RUNNER_DIR}/src/test/java/${PKG_PATH}"
else
  TEST_SRC_DIR="${RUNNER_DIR}/src/test/java"
fi

info "Copying .java files to ${TEST_SRC_DIR} …"
rm -rf "${RUNNER_DIR}/src"
mkdir -p "${TEST_SRC_DIR}"
cp "${TESTS_DIR}"/*.java "${TEST_SRC_DIR}/"

# ---------------------------------------------------------------------------
# 3. Run the tests against the live SUT.
#    testFailureIgnore=true ensures the build continues to the report phase
#    even when tests fail (expected for security/fault tests).
# ---------------------------------------------------------------------------
info "Running JUnit 5 tests with Maven Surefire …"
mvn -f "${RUNNER_DIR}/pom.xml" \
    --batch-mode \
    -DSUT_BASE_URL="${SUT_BASE_URL}" \
    test \
    -Dsurefire.failIfNoSpecifiedTests=false \
  || info "Some tests failed (this is normal for fault/security tests)."

# ---------------------------------------------------------------------------
# 4. Generate the HTML Surefire report.
# ---------------------------------------------------------------------------
info "Generating HTML report …"
mvn -f "${RUNNER_DIR}/pom.xml" \
    --batch-mode \
    surefire-report:report-only

# ---------------------------------------------------------------------------
# 5. Copy report alongside the generated tests so everything is in one place,
#    and print the final location.
# ---------------------------------------------------------------------------
REPORT_SRC="${RUNNER_DIR}/target/site/surefire-report.html"
REPORT_DEST="${TESTS_DIR}/surefire-report.html"

# Also copy the CSS/images Maven site resources need for a standalone report
SITE_SRC="${RUNNER_DIR}/target/site"
SITE_DEST="${TESTS_DIR}/site"

if [[ -f "${REPORT_SRC}" ]]; then
  cp "${REPORT_SRC}" "${REPORT_DEST}"
  # Copy supporting CSS/images so the report renders correctly offline
  if [[ -d "${SITE_SRC}/css" ]]; then
    rm -rf "${SITE_DEST}/css"
    mkdir -p "${SITE_DEST}"
    cp -r "${SITE_SRC}/css" "${SITE_DEST}/"
  fi
  if [[ -d "${SITE_SRC}/images" ]]; then
    rm -rf "${SITE_DEST}/images"
    mkdir -p "${SITE_DEST}"
    cp -r "${SITE_SRC}/images" "${SITE_DEST}/"
  fi
fi

REPORT_XML_DIR="${RUNNER_DIR}/target/surefire-reports"

info "===================================================================="
info "Report generation complete."
info ""
if [[ -f "${REPORT_DEST}" ]]; then
  info "HTML report : ${REPORT_DEST}"
  info ""
  info "To open in a browser:"
  info "  cd ${TESTS_DIR} && python3 -m http.server 8000"
  info "  Open http://localhost:8000/surefire-report.html"
else
  info "HTML report : ${REPORT_SRC}"
  info "  (serve it via: cd ${SITE_SRC} && python3 -m http.server 8000)"
fi
info ""
if [[ -d "${REPORT_XML_DIR}" ]]; then
  info "XML results : ${REPORT_XML_DIR}"
fi
info "===================================================================="
